name: TestLinting

on:
  push:
    branches-ignore: ["main"]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Scheduled test'
        type: boolean

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: |
          npm ci

      - name: Run lint
        run: |
          npm run lint

      - name: Print tag if present
        run: |
          echo "Tags: $TAGS"
        env:
          TAGS: ${{ github.event.inputs.tags }}
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: npm ci
      - name: Run cypress unit tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          start: npm run test:unit
          wait-on: 'http://localhost:3000'
      - name: Run cypress integration tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          start: npm run test:unit
          wait-on: 'http://localhost:3000'
